### PR TITLE
Notes

### PR DESCRIPTION
**Pull request by lgill**
@aila293 @morganhowell95 @jrpotter I tried adding notes to the README on how to do basic branching, pushing, and pulling

### CODE REVIEW

**Comment by morganhowell95** [comment]
@lgill let's try using markup language to format the notes: 

https://help.github.com/articles/markdown-basics/
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by jrpotter** [comment]
Yeah Laura, those notes would be great. Once you set it up with markup I'll make sure to merge the changes (if you need examples you can look at the Django or RoR templates and examine the READMEs in each).

**Comment by lgill** [comment]
@morganhowell95 @jrpotter Does it look more like you would want it to now? Also definitely let me know if I need to edit any of the content. I'm still new at this, so there could definitely be some errors in my notes

**Comment by morganhowell95** [comment]
@lgill  looks great! Thanks for that +1
let me know if you need any help going through the Rails tutorial. Kammy's environment is all set up now.

**Pull request merged**
